UPDATE public.ruminations
SET full_text = $rum$
Those of you who read the No. 1 of this Volume, composed last Spring and focusing on the small problem I had with my back and leg, may notice that I have changed the sub-title of this publication.  Originally it was “A Letter… on Many, but Selected Current Issues and Events”, and the two issues in Vol. I did deal with a related series of issues and events, quoted and then followed by Russell comments.  I continued that sub-title-description in Vol. II, even though all of the quotes, short to very long, were from one source, the Holy Spirit.  That shall be the case again in this letter (and probably henceforth), so I feel that honesty and directness are superior to continuity and tradition as values to follow here.  (Besides, three issues is hardly a hoary tradition.)

Now a few of you understand and appreciate the relevance of this sub-titular declaration.  Some others know what I have said about the teachings I receive, and feel variably about this… from believing that this to which I attest is quite possible… to a refusal to consider this claim at all, reading the letter mostly because I write it… and because it may be moderately interesting.

All right, for those of you who really don’t yet know what I’m talking about, let me offer an abbreviated version of my spiritual story, the impetus for this publication.  I grew up as a good, nominal Christian, participating in activities and programs of the Methodist Church, but with no great spiritual involvement.  (I never consciously encountered anything like I am doing now, so there could be no real rejection… or acceptance… of it.)  In the 1950’s I realized I was a Calvinist, with a developing sense of predestination to some task for which God wanted me.  Also during this decade I became what I have no difficulty identifying as a born-again Christian, though this came in a gradual way rather than through a sudden, dramatic event.  In the same time frame I was introduced to present day prophesies from the Lord God… and also to the concept of reincarnation (which later came to be seen in a Christian perspective.)  Some of these seemed incompatible with others, but I was not much bothered by this.

In the early 1960’s a prophetic message delivered through my mother-in-law, Mabel, urged me to set aside an hour each day and write down what came to me in a kind of meditation (though the term “meditation” was not used very comfortably then.)  I decided to do this and did it for some months, produced some interesting writings, but it was all “me.”  I stopped the “practice” before moving to Southern Illinois, and felt neither loss nor guilt.

My spiritual development continued in these diverse ways, and my professional interests, as a health education professor, were moving toward a holistic perspective… health as the quality of functioning and adapting of the whole person or of “whole” communities – body, mind, and spirit.  As with most professionals I was generally keeping these developments of self unrelated, consciously and unconsciously.  This culminated in an event in May of 1979 in which I was “called” back to a time of meditative writing the first waking hour of the day.  I followed this spiritual leading faithfully and was astounded, two weeks later, to have my pen “taken over” by the Holy Spirit, who began to offer me teachings through my own handwriting, vocabulary, and grammatical and punctuative style.  The essence of the commission which I was offered in these meditations was to help develop the concept of a spiritual dimension to health for my professional field and colleagues.

These writings have continued.  I sit down in a quiet place, usually my study at home, put the date, time and place as a heading and then sit back and wait for a title.  Sometimes immediately and sometimes after some “clearing,” I both “hear” and “see” the title.  I print it atop the page, and the fulfillment of this “starts flowing.”  The result usually comes to three handwritten pages, and the meditation takes about an hour.  At this writing I now have ten volumes of these “originals”, each nearly an inch thick.

Last Spring I used quotes from a number of these as a basis for my Ruminations on an apparently ruptured disk in my lower back, with its accompanying pain and disability.  It is difficult to summarize that letter, but if I had to I’d say that the Spirit taught me this: the injury was, fundamentally, a spiritual experience, and I might heal miraculously, I might improve and heal with exercise over time, or I might have a permanent minor disability… and each possibility would have merit, spiritually.  (The fact is I still have some disability, but less and less, as time goes by, with no specific exercise program to achieve such.)

I have had letters and conversations telling me that this “letter” was of much value to a number of readers, including one who was making an incredible recovery from a massive stroke.  On the other hand, my nephew Mark, a sophomore at Whitworth, wrote:

Uncle Bob, your spirit led writing/teaching is fascinating, and I liked reading your letter.  I would like very much to read more.  Do you have any that deal with more towards the mental/psychological side of man.  Being young and fairly healthy I don’t relate as well to these (the ones on pain and disability) as maybe my Mom…

I knew that this issue should deal with something of this sort, but I wasn’t sure what.  The Spirit decided for me.

In May of 1980 I had an opportunity to make a presentation at a conference in Minnesota, the title of the paper being “The Spiritual as the Unifying Dimension of Health.”  The Spirit provided me four consecutive teachings on this theme in late April, from which I built “my” presentation.  The first paragraph, on April 26, 1980 said this.

There was a question in your mind, o son, as you considered whether to seek Me this drippy morning… a question of whether to seek a new teaching or to seek some synthesis from past teachings for your presentation at Duluth.  The answer came as you sat down and discerned the theme.  I shall give you the essence of the presentation.  Your attention is not good yet, and you are just a bit leery of such a gracious act, but you will hear My words that relate to this opportunity.

So, it is to be that… finally… my introductory story wanes, and the Ruminations commence on the fascinating idea that the spirit can be a unifying and the best coordinating force for the total self… for healthiest being.  In a teaching titled “Ruminations” a bit more than a month ago the Spirit said, rather directly:

You are slow in coming to My direction about the theme, but this is fine with Me.  You have time this morning, so spend a bit more with Me than usual.  You were searching too far and wide.  The answer is basic and simple and obvious: the Spiritual as the Unifying Dimension of Health.  You never did finish the paper you intended to write about those four specific teachings, so now you can compose it in a better format, that already established for Ruminations.  (from “The Unifying Dimension, Apr. 26, 1980.  p. 1)

From a health perspective (my professional one) it is interesting to hear that this unifying force applies not only to individuals… to personal health… but also to relationship and societies… to community health.  This seems to say that the spirit in my Punahou track teams of 1950, 51, and 52, the spirit de corps of the Marine Corps, the spirit for rebuilding in a physically devastated town, for example, are actual, and a force for unifying in accomplishing tasks.  There was an immediate perspective given in the next sentence, however…

Yet because it has the greatest capacity for unification, it also is that which makes for disunity and strife.  But We shall speak mainly of the positive, unifying function of this dimension of being… (from “The Unifying Dimension, Apr. 26, 1980.  p. 1)

There is a kind of general truth that if something – a drug, a machine, an organization – has a high capacity for affecting a positive good, it has a comparable capacity for harm.  The American Civil War was a terrible, destructive war, perhaps because each Army had a spiritual unity and a strong sense that God “was on their side.”  Social, economic, and political problems in the world today seem to be exacerbated when the “foes” are also Protestant vs. Catholic, Moslem vs. Jew, Christian vs. Communist.  But we shall concentrate on the positive in this discussion.

Most fundamentally, the spirit of a person is that which seeks contact with and direction from Me.  The spirit knows that there is a Spirit, and the natural tendency is to seek relationship.  Health is a matter of “to him who hath shall more be given”… the person who has the least resistance… the most openness… to this relationship achieves it most readily and benefits from it most fully.  It gives both protection from spiritual harm and the enhancement of positive power.  (from “The Unifying Dimension,” April 26, 1980.  pp. 1,2)

This Spirit Who speaks to me doesn’t commence with possibilities and variations.  The spirit in a person knows the Spirit exists (not “believes” or “imagines” or even “hopes”) and tries to establish relationship and obtain direction.  This, one could say, is a biased interpretation…or (as I see it)… that this is no wishy-washy, “social scientist” Spirit who speaks.

In spiritual matters the strong get stronger (and, presumably, the weak get weaker).  If one is open to spiritual communion… is not resistant… this is achieved more readily than one who is full of doubts and resistance.  For some reason I developed, my third year of university, a resistance and non-openness to higher mathematics and to sciences based on formulas and calculations.  There is no doubt that this has helped to limit my understanding of science and my capacities to function as a scientist.  In comparable fashion, the scientist who is resistant to spiritual truths and processes is limited in development of spirit… just as I have been in science.

The spirit is the fundamental basis for interaction with others that is of a satisfying, high level, because the spirit is that which considers others equal to or of greater value than self.  The mind builds and preserves the self; the spirit sees others first, even “the least of these…”

The development of spirit brings the development of giving to others… often beyond what they deserve.  Ideal human relationships are those in which spirits encourage giving to others rather than keeping for self.  There is desire to do this, along with faith and trust that this will be the best way to meet one’s own needs… indirectly rather than direction.  (from “The Unifying Dimension”, April 26, 1980.  pp. 2,3)

Here is the basic reason why the spirit enhances interaction with others: its nature is to consider others first… or at least equal to self.  This quote also introduces the idea that mind is self-centered… “Take care of #1, ‘cause nobody else will.”  It is logical to look out for yourself and to consider that others are doing the same.  It is illogical, but truly spiritual, to consider others before self and suppose that they might do likewise.  Can you take the chance of considering others above self?  Aren’t they likely to take advantage of you… play you for a sucker?  Won’t this be seen as weakness… in an individual, a corporation, a nation?  “Yes,” says the rational mind, “protect yourself.”

And, the teaching goes on to say, give to others, even beyond what they deserve.  The mind can grudgingly OK giving to others what each deserves… but not a bit more (maybe even a bit less).  The spirit challenges with a call to give what is deserved… and then more.  In fact, what another “deserves” is really not much of an issue!

Occasionally I take care of two little granddaughters, ages 2 and 3.  My mind says “You have lots of important things to do… give these small ones enough time to minimally satisfy them and keep them safe and out of trouble…”  My spirit says, “Give them all of your time and all of yourself… the other matters can wait… what is more important than two spirits just learning about this world their little bodies are in…”  Mind sometimes wins, I must admit.  It is a powerful competitor with spirit.  But when spirit is strong they can work together much better.

Faith and trust.  These are important to spiritual development and exercise… faith and trust, even when the apparent evidence is slim, that doing for others, genuinely and first, will eventually truly benefit you more than “looking out for #1.”  Faith begets faith.  You don’t develop much faith out of doubting… just as you don’t develop improved physical condition by considering the pros and cons of exercise

So, how is the spirit developed.  In much the same way other health related aspects of self are developed.  Muscles are developed through constant, vigorous use.  The immune system functions best when it must produce its myriad cells to counter actual possible infections.  In like fashion, o son, the spirit is developed and strengthened by use.  First comes awareness… you become increasingly aware of your spirit and of how it would lead you.  Relationship to Me is of supreme importance.  Otherwise, the mind tends to dominate, and the mind is mainly interested in the individual self.  Then as you are aware of the opportunities for service to others… of the value of others… the spirit gets to direct.

When the spirit directs, the unifying effect is of highest quality.  Other dimensions tend to want to dominate.  If the mind is the unifying dimension it tends to favor itself and dominate rather than unify.  But when the spirit is the unifier it considers the others and achieves a better balance.  With better balance comes happier, more productive living.  (from “The Unifying… Continued”, April 27, 1980.  pp. 1,2)

It says, doesn’t it, that the spirit can be developed, and that the first step is awareness.  I think of biofeedback as a physical analog.  In this procedure you become aware of differences in feeling that are present but usually ignored.  Then you become aware of how it feels to change those feelings… reduce that stress or pain.  With practice that awareness translates into functional control, and you can affect changes that formerly came only with medication (if at all).

Again, this Spirit presents no alternatives – relationship with Him is of “supreme importance” for spiritual power.  (And, incidentally, other teachings stress that “Him” is merely convention and style… the Spirit is fully male, fully female, and any combination imaginable.  He said, once,

… I smile at the seriousness of protest at My being He… as well as at the apparent blasphemy (well, almost!) in referring to Me as She.  I’m sorry some women are so “put off” by this whole issue, but it also is pretty amusing… (from “Fun,” Dec. 4., 1979.  p. 3)

Forgive the digression, but this could be important to some.  The power of relationship helps generate the necessary awareness and the motivations to accept and act upon these opportunities for service.  And when the developed spirit directs, it unifies, for it is interested in balance rather than in dominance.  The spirit has no desire to overcome and subdue the mind.  It realizes the important of mind, of learning, of concern for self, of logical and rational action.  The spirit wants only to balance these concerns with physical needs, with social opportunities, and also with the proclivity to think of others before self… to act, sometimes, illogically and joyously.

Now doesn’t this seem to be suggesting that, though there are going to be a variety of balances in a total population, when it comes to those with spirit directing (in relationship with Spirit) they’re going to be pretty similar?  Apparently not…

Know, first, that all of My creatures are not the same.  There are obvious differences in appearance, in language of communication, and in living habits.  So, too, there are great variations in the understanding, acknowledgment, and manifestations of spirit in people and in peoples.  I do not desire that all people shall be alike.  I am pleased with the variegations.

Some of My servants do discern the spirit in the wind, the rocks, the trees.  It is not a question of “is it really there?”  Remember that ultimate reality is not either/or… but both/and.  Feel the spirit wherever you can.  Feel it in the quiet of your pasture.  Feel it in the sad eyes of Prudence.  Feel it in the traffic of a busy street.  Feel it in this meditation as I guide your pen to write insights old and new.  Don’t worry about the spiritual discernments you don’t make.  Just acknowledge and joy in the ones that you do.  Spend no time putting down those who feel spirit differently from you.  Even some of My good servants waste efforts in being protective of Me.  (from “The Unifying… continued,” Apr. 27, 1980.  p. 3)

He says it rather plainly… He does not want all people alike… is pleased with the differences.  This says, I think, that even devout Christians are going to be different from one another.

The referent for “the spirit in the wind, the rocks, the trees”, is a letter written by an Indian Chief in the 1850’s, used by some environmentalists, myself included.  Some Christians, I know, get uncomfortable when there is the suggestion of spirit in inanimate objects or animals.  This sounds pantheistic, pagan… and they feel the need to get you “back on the right track.”  The message here, and extensively in these teachings is “both/and” rather than “either/or.”  To feel the spirit in the wind or in a grove of trees (such as those in which Peter’s body is buried) need not detract from knowing the Spirit through Christ or developing the spirit through prayer and Scripture reading.  It seems to me that the more you try to limit spirit to certain “safe” sources or experiences the more limited your whole spiritual life will be.

Now, within the spirit of these teachings it is important that I preface the preceding statement with, “It seems to me…”  I have my view, and I share it with you and others, but I also accept that some others may feel and affirm that spiritual strength comes from spiritual purity… knowing the “right” sources and denying many others.

Then I go back and note that, to me, the Spirit says, “Feel the spirit wherever you can.”  These are NOT universal messages… but they are scriptural teachings for me and for other who may profit from them.  I learn from them, and then I share.  Get angry with me or feel sorry for me if you have to, but… be sure you have to.

The last portion says it magnificently… don’t worry about what you don’t understand, but focus on and enjoy what you do.  I am not to spend time denigrating those who feel and discern spirit differently from me… those who speak in tongues and have visions… or those who dream spiritually significant dreams… or those who are not sure there is such a thing as spirit.  “Even some of My good servants waste efforts in being protective of Me.”  Doesn’t that sound like a loving, understanding, confident Father?  Those who do this are still sons, still servants, still loved, despite what the Spirit refers to as wasting efforts.

The Church in which son Michael and his wife Wendy are active in California has been embroiled in one law suit coming from the fact that they were referred to as a “cult”… and now another one stemming from a printed statement by one of their bishops stating that another group is a “cult”.  Much money and potential spiritual effort is going into these charges and defenses, all presumably out of a desire to protect God.  This is wasteful, yet there is still a God-directed reason for this church being as it is… so the Spirit tells me.

True enlightenment is the actual, honest feeling of spirit in every event, every artifact of life.  But you cannot reach this by trying.  That is an immutable spiritual principle.  The spirit develops by actual, honest use, not by attempts to “be more spiritual.”  (from “The Unifying… continued”, Apr. 27, 1980, p. 3)

The second of these teachings concluded with the above paragraph.  You can’t become more spiritual by trying to be more spiritual.  So some of those who try very hard progress little, and some of those who never read the Bible and never deliberately pray may be becoming more spiritual through their daily actions.  Remember Jesus said (in different Gospels) both “You must believe… I am the way, the truth and the life…” AND “… inasmuch as you did it unto one of the least of these, My brethren, you did it unto Me.”

Arthur Ford in the book he “sent” to Ruth Montgomery after his death (A World Beyond) tells a story of a good, Christian woman who dies (or so she presumes) and wants to get to the throne of Jesus, where she knows she belongs.  She finds “the path” and starts vigorously along it, passing people, bumping some out of the way, eager to reach her goal.  When she realizes she is really not making progress, she asks an old man why… and he replies, looking at all the others, particularly those she has jostled aside, “You shall not get there until everyone gets there.”  A bit different from “You must walk this lonesome valley… you have to walk it by yourself.”  Yet each of these seems to be a spiritual truth.

A long-remembered quote from C. S. Lewis says it yet another way… “No one will get to heaven unless he’s willing not to go.”

Let us also go back to an earlier truth taught:  that individuals are called to or attracted by and/or “suited for” certain aspects of relationship.  Some will do much helping of those in trouble or with problems… those who need restoring to health.  Everyone will do some of this… some is essential to developing spiritually.  Yet it is true that there are some spiritually akamai folk who will mainly promote the health of spirits already strong and vital.  This is your essential task.  Be certain that, insofar as it is in your power, you approach this with a sense of positive mission.  You should know that this is a positive calling to which you must dedicate yourself.  It is not just “better than dealing with sick people.”  And you must help your small share of such people.  (from “That Which Unifies,” Apr. 27, 1980.  pp. 1,2)

This is interesting to me, of course, because it tells me that I am doing in the world what I should be doing.  It is not superior to nor is it inferior to other careers or relationships… it is just what I should be doing – promoting the health of spirits already strong and vital.  It is also important to know that though my essential life task is not to help those in trouble or with problems, some of this is essential for each of us in order to develop toward spiritual maturity.  I am not a professional counselor, but there will be times when I have the opportunity to counsel… and it is important for me to do so.

(You notice, perhaps, the phrase “some spiritually akamai folk” and you wonder why the Holy Spirit would use such a phrase.  So did I.  Yet I have been told that the Spirit can use any means of communication there is.  I understand “akamai”… though I use it very infrequently here in Southern Illinois… as a Hawaiian word meaning knowledgeable, mature, “with it,” so because I understand He can use this, rather than some Greek, Norwegian, or Aramaic word or phrase, which I would not know.  When you think about it, what language forms would the Holy Spirit use?  Would He be limited to King James English?  If He is supreme teacher and counselor would He not apply a basic educational principle and use language learners could understand?  Anyway, if you still think the Holy Spirit shouldn’t sound like this, please let me know how He should sound?  Or, more in the spirit of dialogue than contention, how He sounds to you.

The spirit is also a means of unifying body parts and functions.  When the spirit is strong and developing, the heart and circulatory system work most efficiently, there is the best digestion of food, and protection from competitive invaders.  The eyes see, the ears hear, and the body moves in tune.  There is a sense of buoyancy, a balance, and incomparable rhythm.  On the other hand, when you encounter a person, such as David, with ills galore, many undiagnosable, the trouble is an underdeveloped spirit that cannot unify all the enzymes, hormones, myriad cells and substances.  Without the unification of spirit, that from the physical body itself, even in concert with the mind, is often inadequate.  (from “That Which Unifies,” Apr. 27, 1980, pp. 2, 3)

The spirit has, so it says, a unifying effect upon body parts and functions.  These work best together when the spirit is strong and “in charge.”  We just assume that all of the infinite interactions within our bodies all go on as they should… just “naturally.”  The David referred to is a friend who has multiple physical, mental, and emotional complaints, goes through many medical tests, which lead to no definite diagnosis.  If the Spirit is right (and I’m more and more likely to assume this is so) then the ills will continue, for this underdeveloped spirit is not sufficient to coordinate what body and mind can’t seem to do either.  And, of course, if he doesn’t realize this, then the physical and emotional problems can cause a further deterioration of spirit, and therefore, even poorer health.  As the last Ruminations taught if he could see the ills as spiritual challenges he could grow from them.  We keep coming back to the spiritual principle that never seems quite fair… “to her who has shall more be given and from her who has little, even what she has shall be taken away.”

I need to comment on the effect of spirit upon the emotions.  When the spirit is positively well developed it is natural that the more positive emotions are felt and expressed much more often.  Love much more than hate… joy much more than anger… desire to share much more than greed… Still the spirit is the unifying dimension, and life is still a rhythm which can have its discordant times.  There may be a good reason for anger, but anger guided by your spirit in tune with My Spirit, can be almost productive.  It is simply a more positive quality of anger.  Its effect on the body, and its effects on others is qualitatively different than anger unguided and undirected by spirit.  (from “The Dimension That Unifies,” April 28, 1980.  pp. 1,2)

This was almost a new idea to me.  I certainly had assumed that one with developed spirit would feel and express the more positive emotions, but was a bit more uncomfortable with what such folk do with anger, hate, greed, and the like.  This says that when these are felt, and they will be, even in those of “big spirit,” they can be guided and directed by the spirit, particularly when there is attunement (or how about at-one-ment?) with the Spirit.  Anger is still anger, but there is a more “productive” quality to it.  I’m not really sure what that means, but I’d say it’s true.  Do you have any experience or observations on this issue?

Following after this is a marvelous two paragraph distinction between love which is spiritual and love, the emotion.

So, also those with undeveloped spirits can feel the emotion of love, but it has no deep root.  The emotion of love can be felt by every person, but those with strong spirits feel love that lasts, that survives crises, that permeates a relationship, a “love that will not let me go.”  The difference is that a fundamental aspect of the spirit is love, for the fundamental nature of Me is Love.  The emotion of love is somewhat like the love that is spirit, but a weak faint copy.  (Feeling love, however, is seductive, and may draw one to develop spirit so that real love can be manifested.)  Those with strong, developed spirits can love much and many, and the loving makes more loving possible… another instance of “to him who hath shall more be given.”

The strong spirited can love when the love is not returned.  They can love enemies… and those who respond with no emotion.  Their love can sustain itself without external reinforcement, whereas those who love, as an emotion, without much spiritual base, need reciprocal love… or else what they feel fades… or turns to hate.  The spirit unifies and it also sustains through periods with no positive reinforcement from without.  (from “The Dimension That Unifies,” April 28, 1980.  p. 2).

It seems to say that feeling the emotion of love can help in the development of spirit… which allows you to love more and more variously, including those who do not seem to love in return.  This brings about even more development of spirit, and loving is felt as worthwhile, even when there is no evidence that it is.  God Himself surely does love in the midst of a lot of “No thank yous.”  Those who have developed spirit through loving, however, can feel, can know of that Love when others are uncertain about its reality and presence.

How about another comment on the mind and spirit, with some words aimed at the original Minnesota presentation, but perhaps just as applicable to these Ruminations?

I have suggested, I hope, that there can be a rivalry, from friendly to almost deadly, between the spirit and the mind or the intellect.  You were just thinking about responding to the source of your presentation.  True, some people would feel more comfortable if you could say you derived these principles from empirical study or could footnote extensively to prove your scholarship.  Put another way, some would feel more uncomfortable with the affirmation that these were presented to you by the Spirit through a process that might be called automatic writing.  On the positive side, however, those with developed spirits will appreciate good, useful principles and apt examples, no matter what their source.

A develop spirit does not demand that all knowledge come from the Spirit… or spirits.  It can appreciate the many intellectual sources of ideas and concepts.  The spirit transforms ideas before using or applying them.  They are simply better because they have been “processed” by spirit.  (from “The Dimension That Unifies,” April 28, 1980.  p. 3)

Importantly it says that the rivalry between mind and spirit can develop (not inevitably), but even when it does it can be a “friendly” competition.  It seems clearly not to be an anti-intellectual stance.  That is, the spirit, when in charge, does not do to the mind what the mind, when it dominates, does to the spirit.

Maybe you are one (be honest with yourself, now) who would respond much more favorably to this whole publication if I confirmed that these were findings from a study of a certain sample of people, using some respectable technique to gather the data.  Or, if each footnote were to a recognized author rather than to a teaching that I claim to have received form the Holy Spirit about a year and a half ago, some would feel more comfortable.  Digression.  When I was having some difficulty getting an adult Sunday morning class, finally called “Morning Meditations in the Spirit”, approved at our Presbyterian Church, it occurred to me that there would be little fuss or ado if I proposed to lead a class on a set of meditations written by a recognized Christian mystic who lived in Europe in the 1500’s.  “Those things” did happen in the past, perhaps, but… now?  Right now?  Anyway, how about the idea that the spirit “transforms” ideas before using and/or applying them?  Thoughts themselves and secular knowledge come to have a different quality when “processed” by the spirit.  Could this be empirically proven?  Probably not.  Is it true, then?  The Spirit says it is.  Where are your loyalties in relation to truth?

In relation to the above, hear an assessment that came near the end of a meditation nearly three months later.

“Proof” of spirit is partly in the self and partly visible to others.  But just as a statistical “proof” is such only to the one sophisticated in this mathematical manipulation, so proof of the spirit is most evident to those of developed spirit.  (from “The ‘Unifier’”, July 13, 1980, p. 1)

How does all of this “work out” in actual living?  Give an example, you implore (don’t you?)  Here is one provided by the Spirit just before I made a presentation on this topic to a graduate class in Human Ecology during the Summer of 1980.

All communication is enhanced by the development of spirit, because it is the spirit that truly reaches out to others… is genuinely concerned with others.  But communication about the spirit is particularly affected.  Those in the class with spirits well developed will hear and comprehend… like unto those who know a dance and can do it well, and can learn others more easily because of this developed ability.

Carry this example on.  You are going to learn a new folk dance.  A certain amount of physical skill and coordination is necessary… you have that.  The emotional climate must be right… you must want to do this and have no “blocks” against such an activity.  You need the mental ability to understand the directions and translate the words into actions and imitate what you see others doing.  Socially you need to be compatible with the others also learning and doing the dance.

But the spirit is that which can unify the whole experience.  The spirit is that which “feels” the rhythm and the significance of the dance, that knows how the dance can be a means of people relating, in positive, joyful ways.  The spirit appreciates the physical coordination and stamina needed, as well as the positive emotions that can override the negative ones.  Those with developed spirits will learn the dance, in its entire context, most easily and most comfortably and will be teaching others most naturally and quickly.  (from “The ‘Unifier’”, July 13, 1980.  pp. 1, 2)

Spirit, of course, doesn’t substitute for physical incapacities, for mental deficiencies, or for emotional imbalances.  Yet this says that when persons have such disabilities a strong spirit can make these seem less obvious, less handicapping.  Several years ago I had in two classes a little, young woman in a wheel chair, terribly deformed and physically weak.  Her printing of assignments took her a painfully long time, but she was never late with a paper.  Her voice was raspy and unpleasant, but the things she said often took away that judgment.  Her spirit was so powerful and so pervasive, that, to me, all of her handicaps seemed really minor.

Think of this example, of learning the dance, the next time you try something new… that involves all of these dimensions.  I’ll testify that it can give a whole different quality to an experience, even a painful one.

As some of you know I do some presentations, hither and yon, using songs and stories, accompanying myself with minimal skill on a tenor guitar.  I know from experience that I can generate spiritual responses with certain songs, and I also have admitted that I have to “feel” a song before I can really learn it.  I play and sing “by ear”… but it may be more “by spirit”.  Naturally, then, this paragraph struck me rather forcefully.

Spiritual interaction can also be indirect.  A person who writes a song can impart a spirit to that song.  In addition (or instead) a person or group who sings the song can impart a spirit.  When your spirit feels the presence of that other spirit (or spirits) you can learn the song more easily, and you can perform it with greater total feeling.  It then communicates better to others… and the others with spirits attuned are those who will hear it as more than just words and music.  They will feel it as music in the soul and in the heart, rather than merely sounds in the ear.  (from “The ‘Unifier’”, July 13, 1980.  pp. 2,3)

And so… you have, if you’re still reading, come along with me on a small journey of faith, revelation, and stimulus of spirit.  I shall be writing another of these in a few more months and plan on four a year.  Once I get the rhythm established I know I shall have little trouble achieving this goal… with all the “raw data” that I have to jaggle my ruminative nature.  But I have one more teaching that I must share.  It is directed to me, personally, but if it seems to ring your chimes in any way (and I’m sure this will be true for some)… you’re welcome!

Spirit inheres in so much of the world.  It is the task of some to proclaim the differences between spirit and flesh… or other worldly things.  Your task is more one of encouraging the perception of spirit in the interplay of people and with the earth and its natural and manufactured “things”.  Feel the spirit in the clover as you cut it… in the rabbits you raise… in the breakfast, whatever its content… in the talk with Matthew… in the beautiful and in the frustrating experiences of the day.

Oh, you needn’t try to discern spirit in everything.  You are not far enough along to do that.  But be increasingly aware.  You feel all the potential opportunities during this meditation time, but much less as your regular day takes over.  Seek a better balance.  Not radical change… just an altered rhythm.  (from “The Spiritual Dimension,” April 15, 1981.  p. 3)

And thus I urge you… be increasingly aware.  Write to me of experiences… give me examples… for the spiritual as a significant factor in health, functioning and adapting, shall be my major area of research and composition for the next 15 years of my career.

May love abound, in you, as it does in me.

Shalom

Bob Russell

Christian, Professor, Writer, Song-Singer,

Farmer, Philosopher, Servant
$rum$
WHERE slug = 'vol-2-no-2';
